version: "3.3"

services:
  traefik:
    image: traefik:v2.4.5
    command:
      - "--api.insecure=true"
      - "--metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role==manager]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  whoami:
    image: "traefik/whoami"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 3
networks:
  traefik:
